#!/bin/bash

# this script creates 2 network namespaces
# both of this namespaces connect to hosts's bridge

# $NS1 - name of the namespace 1
# $NS2 - name of the namespace 2

. env.sh

echo "Creating the namespaces"
sudo ip netns add $NS1
sudo ip netns add $NS2

echo "Creating the veth pairs"
sudo ip link add veth10 type veth peer name veth11
sudo ip link add veth20 type veth peer name veth21

echo "Adding veth pairs to the namespaces"
sudo ip link set veth11 netns $NS1
sudo ip link set veth21 netns $NS2

echo "Configuring the interfaces in the network namespaces with an ip address"
sudo ip netns exec $NS1 ip addr add 172.16.0.10/24 dev veth11
sudo ip netns exec $NS2 ip addr add 172.16.0.11/24 dev veth21

echo "Enabling the interfaces inside the network namespaces"
sudo ip netns exec $NS1 ip link set dev veth11 up
sudo ip netns exec $NS2 ip link set dev veth21 up

echo "Creating the bridge"
sudo ip link add name br0 type bridge

echo "Enabling veth interfaces on the host"
sudo ip link set veth10 up
sudo ip link set veth20 up

echo "Adding the network namespaces interfaces to the bridge"
sudo ip link set dev veth10 master br0
sudo ip link set dev veth20 master br0

echo "Assigning the IP address to the bridge"
sudo ip addr add 172.16.0.1/24 dev br0

echo "Enabling the bridge"
sudo ip link set dev br0 up

echo "Enabling the loopback interfaces in the network netspaces"
sudo ip netns exec $NS1 ip link set lo up
sudo ip netns exec $NS2 ip link set lo up

echo "Setting the route on the node"
sudo ip r add 172.16.0.0/24 dev br0

echo "Setting the default routes in the network namespaces"
sudo ip netns exec $NS1 ip r add default via 172.16.0.1 dev veth11
sudo ip netns exec $NS1 ip r add 172.16.0.0/24 dev veth11
sudo ip netns exec $NS2 ip r add default via 172.16.0.1 dev veth21
sudo ip netns exec $NS2 ip r add 172.16.0.0/24 dev veth21
